### ISSUE TITLE
3x Assets

### ISSUE THREAD

**Issue by RubenSandwich** [cmoa/cmoa-app-ios#10]
3x assets need to be provided in order to better support the iPhone 6+.

List of assets that need a 3x version:
- [ ] nav_facebook.png
- [ ] nav_twitter.png
- [ ] id_audio.png
- [ ] id_video.png
- [ ] button_recommend_on.png
- [ ] button_recommend_off.png
- [ ] page_off.png
- [ ] page_on.png
- [ ] button_search_on.png
- [ ] button_search_off.png
- [ ] button_video_on.png
- [ ] button_info_normal.png
- [ ] button_pause_normal.png
- [ ] button_play_normal.png
- [ ] tab_category_off.png
- [ ] tab_category_on.png
- [ ] tab_artwork_off.png
- [ ] tab_artwork_on.png
- [ ] tab_code_off.png
- [ ] tab_code_on.png
- [ ] tab_title_off.png
- [ ] tab_title_on.png
- [ ] tab_location_off.png
- [ ] tab_location_on.png
- [ ] tab_share_off.png
- [ ] tab_share_on.png
- [ ] tab_next_off.png
- [ ] tab_next_on.png
- [ ] tab_prev_off.png
- [ ] tab_prev_on.png
- [ ] tab_bg.png
- [ ] button_open_safari.png
- [ ] nav_bg.png
- [ ] nav_back.png
- [ ] nav_menu.png

**Comment by RubenSandwich** [comment]
List of assets needed to be updated:

- [ ] nav_facebook.png
- [ ] nav_twitter.png
- [ ] id_audio.png
- [ ] id_video.png
- [ ] button_recommend_on.png
- [ ] button_recommend_off.png
- [ ] page_off.png
- [ ] page_on.png
- [ ] button_search_on.png
- [ ] button_search_off.png
- [ ] button_video_on.png
- [ ] button_info_normal.png
- [ ] button_pause_normal.png
- [ ] button_play_normal.png
- [ ] tab_category_off.png
- [ ] tab_category_on.png
- [ ] tab_artwork_off.png
- [ ] tab_artwork_on.png
- [ ] tab_code_off.png
- [ ] tab_code_on.png
- [ ] tab_title_off.png
- [ ] tab_title_on.png
- [ ] tab_location_off.png
- [ ] tab_location_on.png
- [ ] tab_share_off.png
- [ ] tab_share_on.png
- [ ] tab_next_off.png
- [ ] tab_next_on.png
- [ ] tab_prev_off.png
- [ ] tab_prev_on.png
- [ ] tab_bg.png
- [ ] button_open_safari.png
- [ ] nav_bg.png
- [ ] nav_back.png
- [ ] nav_menu.png

**Comment by staticmade** [comment]
Dimitry doesn't have the original vectors, so to meet deadlines I'm going to close this. We can address in future dev cycles.

**Comment by RubenSandwich** [comment]
Alright thanks for checking up on this. What about the app Icon and splash screen, do we have those assets as we need other versions of those as well. (I haven't gotten around to filing those issues yet.)

**Comment by staticmade** [comment]
Let's let those ride too...I'm not going to be able to do much of anything
other than the Specular workshop this week, and then I'm traveling next.
