### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by RubenSandwich** [cmoa/cmoa-app-ios#15]
When updating the base SDK to IOS 9.0, it opened up lots of compiler warnings. Quite a few of them are very simple using int with NSInteger, which is a long on 64 bits systems.

**Comment by RubenSandwich** [comment]
I also need to fix storyboard issues.

**Comment by RubenSandwich** [comment]
One storyboard issue left: "scrollable content size is ambiguous for scroll view."

I'm not going to fix this warning, as it does not negatively effect the layout of the view but is very cumbersome to silence. (About 2 hours plus of work.) Does that sound good to you @staticmade?

**Comment by staticmade** [comment]
Cool.
