### ISSUE TITLE
Exhibition View: Remove "Meet the Artists"

### ISSUE THREAD

**Issue by staticmade** [cmoa/cmoa-app-ios#5]
- Remove "Meet the Artists"
- Leave only "Discover the Artwork" and "Explore the Tours"

![2015-09-21 11 36 33](https://cloud.githubusercontent.com/assets/3757910/9996534/62578920-6055-11e5-946d-cee1a4eefed6.png)

**Comment by RubenSandwich** [comment]
This issue can be closed as it is implemented in the current beta build.
